"""
Generate the e-paper font headers used by the sketch from the Inter TTFs in
tools/fonts (SIL Open Font License, see Inter-LICENSE.txt).

Based on LilyGo-EPD47/scripts/fontconvert.py, with three additions:
  * each font gets only the glyphs it needs (the big numeral font is digits only),
  * the degree sign and ellipsis are included,
  * digits use Inter's tabular figures, so numbers keep their width as they change.

Usage:  python tools/make_fonts.py        (requires: pip install freetype-py)
Writes: Bambu_Monitor_ESP32/font_*.h
"""
import math
import os
import zlib

import freetype

HERE = os.path.dirname(os.path.abspath(__file__))
FONTS = os.path.join(HERE, "fonts")
OUT = os.path.join(HERE, "..", "Bambu_Monitor_ESP32")

ASCII = [(32, 126)]
TEXT = [(32, 126), (0xB0, 0xB0), (0x2026, 0x2026)]   # + degree sign, ellipsis
DIGITS = [(32, 32), (37, 37), (45, 45), (48, 57)]    # space % - 0-9

# (C name, file, size in pt at the panel's nominal 150 dpi, glyph intervals)
FONTS_TO_BUILD = [
    ("InterNumeral", "InterDisplay-Bold.ttf",     72, DIGITS),   # progress percentage
    ("InterTitle",   "InterDisplay-SemiBold.ttf", 26, TEXT),     # key values
    ("InterBody",    "Inter-Medium.ttf",          16, TEXT),     # job name, body text
    ("InterLabel",   "Inter-SemiBold.ttf",        10, ASCII),    # small caps labels
]

DIGIT_NAMES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]


def norm_floor(v):
    return int(math.floor(v / 64))


def norm_ceil(v):
    return int(math.ceil(v / 64))


def load(face, cp):
    index = 0
    if 48 <= cp <= 57:
        index = face.get_name_index((DIGIT_NAMES[cp - 48] + ".tf").encode())
    if not index:
        index = face.get_char_index(cp)
    if not index:
        raise ValueError(f"U+{cp:04X} missing")
    face.load_glyph(index, freetype.FT_LOAD_RENDER)


def build(name, file, size, intervals):
    face = freetype.Face(os.path.join(FONTS, file))
    face.set_char_size(size << 6, size << 6, 150, 150)

    data, glyphs = bytearray(), []
    for start, end in intervals:
        for cp in range(start, end + 1):
            load(face, cp)
            bm = face.glyph.bitmap
            packed = bytearray()
            for row in range(bm.rows):
                line = bm.buffer[row * bm.pitch: row * bm.pitch + bm.width]
                for x in range(0, bm.width, 2):
                    lo = line[x] >> 4
                    hi = (line[x + 1] & 0xF0) if x + 1 < bm.width else 0
                    packed.append(lo | hi)
            comp = zlib.compress(bytes(packed))
            glyphs.append((bm.width, bm.rows, norm_floor(face.glyph.advance.x),
                           face.glyph.bitmap_left, face.glyph.bitmap_top,
                           len(comp), len(data), cp))
            data += comp

    lines = ["#pragma once", '#include "epd_driver.h"',
             f"// Generated by tools/make_fonts.py from {file} at {size} pt. Do not edit.",
             f"const uint8_t {name}Bitmaps[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[i:i + 16]))
    lines.append("};")
    lines.append(f"const GFXglyph {name}Glyphs[] = {{")
    for g in glyphs:
        ch = chr(g[7])
        label = "<backslash>" if ch == "\\" else ch if g[7] < 128 else f"U+{g[7]:04X}"
        lines.append("    { " + ", ".join(str(v) for v in g[:7]) + f" }}, // {label}")
    lines.append("};")
    lines.append(f"const UnicodeInterval {name}Intervals[] = {{")
    offset = 0
    for start, end in intervals:
        lines.append(f"    {{ 0x{start:X}, 0x{end:X}, 0x{offset:X} }},")
        offset += end - start + 1
    lines.append("};")
    lines += [f"const GFXfont {name} = {{",
              f"    (uint8_t*){name}Bitmaps,",
              f"    (GFXglyph*){name}Glyphs,",
              f"    (UnicodeInterval*){name}Intervals,",
              f"    {len(intervals)},",
              "    1,",
              f"    {norm_ceil(face.size.height)},",
              f"    {norm_ceil(face.size.ascender)},",
              f"    {norm_floor(face.size.descender)},",
              "};", ""]

    path = os.path.join(OUT, f"font_{name[5:].lower()}.h")
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{name:13s} {size:3d} pt  {len(glyphs):3d} glyphs  {len(data):6d} bytes -> {os.path.basename(path)}")


if __name__ == "__main__":
    for spec in FONTS_TO_BUILD:
        build(*spec)
